# action.yml
name: 'pushover-actions'
description: 'Push notifications for github repository changes through pushover'
branding:
  icon: 'package'
  color: 'red'

runs:
  using: 'docker'
  image: 'Dockerfile'
